<?php
    $pageHeading = "Page Heading";

    if (defined("PAGEHEADING")) {
        $pageHeading = PAGEHEADING;
    }

    if (defined("PAGEDESCRIPTION")) {
        $pageDescription = PAGEDESCRIPTION;
    }

?>

<div class="page" id="page">
    
    <div class="page-header" id="page_header">
        
        <h1 class="page-title" id="page_title">
            <?php
                if (defined("PAGEHEADING")) {
                    echo PAGE_HEADING;
                } else {
                    echo "Trips2Italy";
                }
            ?>
        </h1>

        <?php
            if (defined("PAGEDESCRIPTION")) {
                echo "<p class='page-description'>" . PAGEDESCRIPTION . "</p>";
            }

        ?>
        
        <ol class="breadcrumb ">
            <li class="breadcrumb-item"><a href="/">Home</a></li>
            <?php
                if (defined("BREADCRUMBS")) {
                    echo BREADCRUMBS;
                }
            ?>
        </ol>
        
        <div class="page-header-actions">
            <?php echo (isset($page_heading_buttons)) ? $page_heading_buttons : "&nbsp;"; ?>
        </div>
    
    </div>
    
    <div class="page-content container-fluid p-0">
        <?php
            if (defined("MAIN")) {
                include_once(MAIN);
            }
        ?>
    </div>

</div>
